name: Deploy Production

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'npm'
      - name: Create .env file
        run: echo "${{secrets.ENV_PRODUCTION}}" > .env
      - run: npm i
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/do-an-cnpm
            git fetch --all
            git reset --hard origin/main
            echo "${{secrets.ENV_PRODUCTION}}" > .env
            npm i
            pm2 restart 0
            pm2 restart 4
